/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Moshiur-Rahman
 */
public class AddMember extends javax.swing.JFrame {

    /**
     * Creates new form AddMember
     */
    public AddMember() {
        initComponents();
        setDefaultCloseOperation(AddMember.DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        tableDb();

        Summery rp = new Summery();
        rp.loadAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEPhone = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtNid = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtAddr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDisplay = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        adddate = new com.toedter.calendar.JDateChooser();
        updateButton = new javax.swing.JButton();

        jLabel15.setText("jLabel15");

        jTextField9.setText("jTextField9");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD NEW MEMBER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 576, 54));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 85, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Age :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("NID :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 178, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Address :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 218, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Phone Number :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 266, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Emergency Number :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 306, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Date :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 346, -1, -1));

        txtEPhone.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(txtEPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 308, 200, -1));

        txtPhone.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 268, 200, -1));

        txtNid.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(txtNid, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 178, -1, -1));

        txtAge.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 130, -1, -1));
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 92, 200, 20));

        btnSave.setBackground(new java.awt.Color(249, 254, 247));
        btnSave.setForeground(new java.awt.Color(51, 51, 51));
        btnSave.setText("Submit");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 450, -1, -1));

        jButton3.setBackground(new java.awt.Color(249, 254, 247));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 450, 80, -1));

        txtAddr.setPreferredSize(new java.awt.Dimension(200, 20));
        getContentPane().add(txtAddr, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 219, 200, -1));

        tableDisplay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "name", "age", "nid", "address", "phone", "emergency phone", "date"
            }
        ));
        jScrollPane1.setViewportView(tableDisplay);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 87, 540, 400));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("Present Members");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 60, -1, -1));
        getContentPane().add(adddate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 200, -1));

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String name, age, nid, address, phone, emerPhone;
        name = txtName.getText();
        age = txtAge.getText();
        nid = txtNid.getText();
        address = txtAddr.getText();
        phone = txtPhone.getText();
        emerPhone = txtEPhone.getText();
        String da = new SimpleDateFormat("yyyy-MM-dd").format(adddate.getDate());

        Connection con = null;
        Statement st = null;

        try {
            //Register the driver class
            Class.forName("com.mysql.jdbc.Driver");

            //Create the connection object
            con = DBConnection.getDBConnection();

            con.setAutoCommit(false);
            st = con.createStatement();

            st.addBatch("insert into members(name,age,nid,address,phone_number,emergency_number,date) values('" + name + "','" + age + "','" + nid + "','" + address + "','" + phone + "','" + emerPhone + "','" + da + "')");
            st.addBatch("INSERT INTO deposit_1(name,date) values ('" + name + "', '" + da + "') ");
            st.addBatch("INSERT INTO meal1(name,adate) VALUES('" + name + "','" + da + "')");
            st.addBatch("insert into nn(name,date) values('" + name + "','" + da + "')");

            int counts[] = st.executeBatch();
            if (counts.length > 0) {
                con.commit();
                JOptionPane.showMessageDialog(this, "inserted successfully");
            } else {
                JOptionPane.showMessageDialog(this, "insertion failed");
            }

        } catch (SQLException ex) {

            if (con != null) {
                try {
                    con.rollback();
                } catch (SQLException ex1) {
                    ex1.printStackTrace();
                }
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddMember.class.getName()).log(Level.SEVERE, null, ex);
        } finally {

            try {

                if (st != null) {
                    st.close();
                }
                if (con != null) {
                    con.close();
                }

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    public void tableDb() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DBConnection.getDBConnection();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from members");
            tableDisplay.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtName.setText("");
        txtAge.setText("");
        txtNid.setText("");
        txtAddr.setText("");
        txtPhone.setText("");
        txtEPhone.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        UpdateMember um = new UpdateMember();
        um.setVisible(true);
    }//GEN-LAST:event_updateButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser adddate;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTable tableDisplay;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEPhone;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNid;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
